### ISSUE TITLE
blog is unilingual

### ISSUE THREAD

**Issue by talnetd** [JockiHendry/JockiHendry.github.io#2]
I guess it is only fair for you to write your blog in English and the rest of the world would inspire your knowledge and do great things. 

Your TAL

**Comment by JockiHendry** [comment]
Thank you for the suggestion, Tin :smile:

**Comment by talnetd** [comment]
Are you going to implement this or not ?

**Comment by JockiHendry** [comment]
I might write new post in English when it is appropriate but there's no plan to translate existing posts, @talnetd.
